[phases.setup]
nixPkgs = ["python311", "pipenv", "openssl", "postgresql", "git"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py migrate"]

[phases.start]
cmd = "python manage.py runserver 0.0.0.0:$PORT"
