# Generated by Django 5.1.1 on 2025-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='recommended_courses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='user_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
