# Generated by Django 5.1.1 on 2025-06-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_userfeedback_recommended_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='most_accurate',
            field=models.TextField(blank=True),
        ),
    ]
