# Generated by Django 5.1.1 on 2025-06-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_userfeedback_most_accurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='mind_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
