# Generated by Django 5.1.1 on 2025-06-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_userfeedback_age_userfeedback_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='mind_type',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='demographics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
