# Generated by Django 5.1.1 on 2024-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_code', models.CharField(max_length=50)),
                ('discipline_name', models.CharField(max_length=255)),
                ('discipline_percentage_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discipline_leading', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizational_unit_uuid', models.UUIDField()),
                ('organizational_unit_full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('course_uuid', models.UUIDField(unique=True)),
                ('isced_name', models.CharField(max_length=255)),
                ('legal_basis_type_code', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=100)),
                ('main_institution_uuid', models.UUIDField()),
                ('supervising_institution_uuid', models.UUIDField(blank=True, null=True)),
                ('liquidation_date', models.DateField(blank=True, null=True)),
                ('level_code', models.CharField(max_length=10)),
                ('legal_basis_number', models.CharField(max_length=255)),
                ('current_status_code', models.CharField(max_length=10)),
                ('leading_institution_voivodeship', models.CharField(max_length=100)),
                ('teacher_training', models.BooleanField()),
                ('leading_institution_city', models.CharField(max_length=255)),
                ('isced_code', models.CharField(max_length=100)),
                ('co_led', models.BooleanField()),
                ('course_old_code', models.CharField(blank=True, max_length=100, null=True)),
                ('main_institution_kind', models.CharField(max_length=255)),
                ('current_status_name', models.CharField(max_length=255)),
                ('main_institution_kind_code', models.CharField(max_length=10)),
                ('last_refresh', models.DateTimeField()),
                ('legal_basis_type_name', models.CharField(max_length=255)),
                ('level_name', models.CharField(max_length=100)),
                ('leading_institution_voivodeship_code', models.CharField(max_length=10)),
                ('creation_date', models.DateField()),
                ('supervising_institution_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('leading_institution_name', models.CharField(max_length=255)),
                ('philological', models.BooleanField()),
                ('leading_institution_is_foreign', models.BooleanField()),
                ('profile_code', models.CharField(max_length=10)),
                ('main_institution_name', models.CharField(max_length=255)),
                ('data_source', models.CharField(max_length=255)),
                ('disciplines', models.ManyToManyField(to='courses.discipline')),
                ('organizational_units', models.ManyToManyField(to='courses.organizationalunit')),
            ],
        ),
    ]
