# Generated by Django 5.1.1 on 2025-04-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_course_city_course_current_status_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=10)),
                ('subcategory', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='feature',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coursefeaturescore',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursefeaturescore',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='userquizanswer',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='userquizanswer',
            name='user',
        ),
        migrations.CreateModel(
            name='CourseQuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CourseFeatureScore',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='UserQuizAnswer',
        ),
    ]
