# Generated by Django 5.1.1 on 2025-04-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question_remove_feature_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='question',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
