# Generated by Django 5.1.1 on 2025-06-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_question_subcategory_question_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reverse_scored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
